Vagrant.configure('2') do |config|
    # INPUT PAYLOAD
    payload_file=File.expand_path('./env.yaml')
    puts "# PAYLOAD: #{payload_file}"
    payload=YAML.load_file(payload_file)['esxi']
    puts payload

    # OS image
    config.vm.box = payload['vm']['box']

    # PLUGINS
    config.vagrant.plugins = payload['plugins']
  
    #  Use rsync and NFS synced folders. (or disable them)
    #    https://www.vagrantup.com/docs/synced-folders/
    #config.vm.synced_folder('.', '/vagrant', type: 'rsync')
    config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)

    #
    #  Provider (esxi) settings
    #
    config.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = payload['host']
      esxi.esxi_username = payload['user']
      esxi.esxi_password = payload['password']
      esxi.esxi_disk_store = payload['vm']['datastore']
      esxi.guest_memsize = payload['vm']['ram']
      esxi.guest_numvcpus = payload['vm']['vcpu']
      esxi.guest_boot_disk_size = payload['vm']['disk']
    end
  end