
Vagrant.configure("2") do |config|

  vm = ["server", "client"]
  vm.each do |name|
    config.vm.define vm_name = name do |node|
      node.vm.box = "generic/ubuntu1804"
      node.vm.hostname = name

      if name == vm.last
        node.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
          ansible.limit = "all"
        end
      end
    end
  end
end
